package com.Sristi.AR_Furniture_Placement.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2C2928)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEF4981)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF65615E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEF4981)
val md_theme_light_onSecondaryContainer = Color(0xFF2C160B)
val md_theme_light_tertiary = Color(0xFF655F31)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEF4981)
val md_theme_light_onTertiaryContainer = Color(0xFF1F1C00)
val md_theme_light_error = Color(0xFF9C27B0)
val md_theme_light_errorContainer = Color(0xFFEF4981)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF9C27B0)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFEF4981)
val md_theme_light_onSurfaceVariant = Color(0xFF52443D)
val md_theme_light_outline = Color(0xFF85736C)
val md_theme_light_inverseOnSurface = Color(0xFFEF4981)
val md_theme_light_inverseSurface = Color(0xFF362F2C)
val md_theme_light_inversePrimary = Color(0xFFB835D0)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF9C27B0)
val md_theme_light_outlineVariant = Color(0xFF9C27B0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFEF4981)
val md_theme_dark_onPrimary = Color(0xFF020202)
val md_theme_dark_primaryContainer = Color(0xFF5B524F)
val md_theme_dark_onPrimaryContainer = Color(0xFF000000)
val md_theme_dark_secondary = Color(0xFF65615E)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFFEF4981)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_tertiary = Color(0xFF655F31)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFF4C481C)
val md_theme_dark_onTertiaryContainer = Color(0xFFEF4981)
val md_theme_dark_error = Color(0xFF000000)
val md_theme_dark_errorContainer = Color(0xFF090909)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFFEF4981)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEF4981)
val md_theme_dark_surface = Color(0xFFFFFBFF)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF52443D)
val md_theme_dark_onSurfaceVariant = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFFA08D85)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DB)
val md_theme_dark_inversePrimary = Color(0xFF030303)
val md_theme_dark_shadow = Color(0xFFFFFFFF)
val md_theme_dark_surfaceTint = Color(0xFF000000)
val md_theme_dark_outlineVariant = Color(0xFF52443D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFEF4981)
